[project]
name = "indicium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.27",
    "langchain-ollama>=0.3.9",
    "langgraph>=0.6.8",
    "ollama>=0.6.0",
]
